/* ============================================================================
   doc-data.js — Trích xuất THẬT từ 2 tài liệu trong data/vlearn-pack/slides/:
     - d1-slide-hackathon.pdf  → AI IN ACTION Day 1: AI & LLM Foundation
     - d2-slide-hackathon.pdf  → AI IN ACTION Day 2: Xác định bài toán cho AI
   Trích bằng pdftotext -enc UTF-8, làm sạch watermark trang trí
   ("AI IN ACTION - HACKATHON" chồng chữ theo chiều dọc), giữ nguyên nội
   dung. Không còn dùng dữ liệu giả (mock-doc.js đã bỏ).
   Mỗi mục: {doc, page, title, key[] (để mock-retrieval match), text}
   ============================================================================ */
window.DOC_META = {"d1":{"file":"d1-slide-hackathon.pdf","name":"AI IN ACTION — Day 1: AI & LLM Foundation","pages":29},"d2":{"file":"d2-slide-hackathon.pdf","name":"AI IN ACTION — Day 2: Xác định bài toán cho AI","pages":29}};
window.DOC_CORPUS = [
 {
  "doc": "d1",
  "page": 1,
  "title": "AI & LLM Foundation",
  "key": [
   "llm",
   "foundation",
   "bạn",
   "đang",
   "dùng",
   "mỗi",
   "ngày",
   "nhưng",
   "thực",
   "bên",
   "làm"
  ],
  "text": "AI & LLM Foundation — Bạn đang dùng AI mỗi ngày, nhưng thực sự bên trong nó đang làm gì?"
 },
 {
  "doc": "d1",
  "page": 2,
  "title": "Agenda (Day 1)",
  "key": [
   "agenda",
   "day",
   "bức",
   "tranh",
   "tầng",
   "lịch",
   "năm",
   "bên",
   "llm",
   "chế",
   "vận",
   "hành",
   "đến",
   "agent"
  ],
  "text": "- Day 1 | Agenda | • Bức tranh AI & các tầng của AI • Lịch sử AI 70 năm • Bên trong LLM: cơ chế vận hành • Từ LLM đến AI Agent | N • Landscape: model hôm nay & cuộc đua hiện tại • Chọn model & chi phí token • Gọi API lần đầu • Tổng kết — những ý để mang về | - | AI & LLM Foundation | Từ \"nghe AI\" đến \"gọi AI\" trong một ngày"
 },
 {
  "doc": "d1",
  "page": 3,
  "title": "AI, ML, Deep Learning, GenAI, LLM — nằm ở đâu trong cùng một hệ?",
  "key": [
   "deep",
   "learning",
   "genai",
   "llm",
   "nằm",
   "đâu",
   "rộng",
   "đến",
   "hẹp",
   "artificial",
   "intelligence",
   "machine",
   "generative",
   "gpt"
  ],
  "text": "AI, ML, Deep Learning, GenAI, LLM — nằm ở đâu trong cùng một hệ? | từ rộng đến hẹp | AI | ARTIFICIAL INTELLIGENCE MACHINE LEARNING | DEEP LEARNING GENERATIVE AI | LLM | N GPT · Claude · Kimi văn bản · ảnh · code nhận diện ảnh · giọng nói | lọc spam · gợi ý phim | - | AI — chiếc ô lớn nhất: mọi hệ thống có yếu tố “thông minh”. | Machine learning — học từ dữ liệu thay vì viết luật tay. | Deep learning — mạng nơ-ron nhiều tầng tự học đặc trưng. | Generative AI — sinh nội dung mới: văn bản, ảnh, code. | LLM — model nền chuyên ngôn ngữ, tim của làn sóng hiện nay. | LLM không phải toàn bộ AI — nhưng nó là tầng | kể cả hệ luật tay, robot… | nền của gần hết trải nghiệm AI bạn dùng hôm nay"
 },
 {
  "doc": "d1",
  "page": 4,
  "title": "Ba nhóm AI chính: phân loại · sinh nội dung · hành động",
  "key": [
   "nhóm",
   "chính",
   "phân",
   "loại",
   "sinh",
   "nội",
   "dung",
   "hành",
   "động",
   "discriminative",
   "generative",
   "agentic",
   "giỏi",
   "đoán"
  ],
  "text": "Ba nhóm AI chính: phân loại · sinh nội dung · hành động | Discriminative AI | Generative AI | Agentic AI | Giỏi phân loại, dự đoán: lọc spam, phát | N hiện gian lận, nhận diện ảnh. Input → một nhãn, một con số | Sinh ra thứ mới: văn bản, ảnh, code. ChatGPT, Claude, Midjourney. | Prompt → nội dung mới | Nhận mục tiêu rồi tự làm nhiều bước: lập kế hoạch, dùng công cụ, hành động. | Goal → Plan → Action | - LLM là engine chung của cả Generative lẫn Agentic — cuối buổi sáng mình sẽ thấy agent khác LLM ở đâu | Hành trình khóa học: LLM Foundation → Agent → Multi-Agent → Deploy → Evaluate"
 },
 {
  "doc": "d1",
  "page": 5,
  "title": "Lịch sử AI 70 năm",
  "key": [
   "lịch",
   "năm",
   "khai",
   "sinh",
   "lời",
   "hứa",
   "đầu",
   "tiên",
   "lần",
   "mùa",
   "đông",
   "cách",
   "tiếp",
   "cận"
  ],
  "text": "Lịch sử AI 70 năm | Khai sinh, lời hứa đầu tiên | 2 lần mùa đông, cách tiếp cận chạm trần | Từ model đơn lẻ sang system có khả năng hành động như | agent"
 },
 {
  "doc": "d1",
  "page": 6,
  "title": "1980: Hệ chuyên gia (expert system)",
  "key": [
   "1980",
   "chuyên",
   "gia",
   "expert",
   "system",
   "đặt",
   "lại",
   "vấn",
   "chỉ",
   "giải",
   "thật",
   "tốt",
   "loại",
   "bài"
  ],
  "text": "1980: Hệ chuyên gia (expert system) | Đặt lại vấn đề: \"Nếu AI chỉ giải thật tốt một loại bài toán chuyên môn hẹp thì sao?\" → Sự ra đời của expert systems AI đổi chiến lược: thôi theo đuổi trí tuệ tổng quát và tập trung giải thật tốt một miền hẹp bằng cách mã hóa tri thức chuyên gia thành luật"
 },
 {
  "doc": "d1",
  "page": 7,
  "title": "2009: Fei-Fei Li và ImageNet — cuộc cách mạng của dữ liệu",
  "key": [
   "2009",
   "fei",
   "imagenet",
   "cuộc",
   "cách",
   "mạng",
   "liệu",
   "ngành",
   "chạy",
   "theo",
   "thuật",
   "toán",
   "thông",
   "minh"
  ],
  "text": "2009: Fei-Fei Li và ImageNet — cuộc cách mạng của dữ liệu | - Trong khi cả ngành chạy theo thuật toán thông minh hơn, Fei-Fei Li chọn con đường khác: xây bộ | dữ liệu lớn hơn — 14 triệu ảnh được gán nhãn tay, hơn 20.000 loại vật. Ba năm sau, chính bộ dữ liệu đó là sân khấu cho cú nổ AlexNet 2012 → bài học định hình cả kỷ nguyên: đôi khi dữ liệu tốt hơn đánh bại thuật toán khôn hơn. | Deng, J. et al. (2009), “ImageNet: A Large-Scale Hierarchical Image Database”, CVPR — doi.org/10.1109/CVPR.2009.5206848 · Fei-Fei Li, TED 2015 — ted.com"
 },
 {
  "doc": "d1",
  "page": 8,
  "title": "2017: Transformer",
  "key": [
   "2017",
   "transformer",
   "bước",
   "ngoặt",
   "hình",
   "hiểu",
   "ngôn",
   "ngữ",
   "theo",
   "cách",
   "linh",
   "hoạt",
   "hơn",
   "mỗi"
  ],
  "text": "2017: Transformer | Transformer là bước ngoặt vì nó cho mô hình hiểu ngôn ngữ theo cách linh hoạt hơn: mỗi từ có thể nhìn sang những từ quan trọng khác trong cả câu, thay vì chỉ đi tuần tự từng bước → trở thành nền móng kỹ thuật cho GPT, BERT và toàn bộ làn sóng LLM sau đó."
 },
 {
  "doc": "d1",
  "page": 9,
  "title": "2022: ChatGPT",
  "key": [
   "2022",
   "chatgpt",
   "xuất",
   "hiện",
   "trải",
   "nghiệm",
   "đại",
   "chúng",
   "lần",
   "đầu",
   "tiên",
   "rất",
   "đông",
   "người"
  ],
  "text": "2022: ChatGPT | ChatGPT xuất hiện như một trải nghiệm đại chúng Lần đầu tiên rất đông người dùng phổ thông có thể trực tiếp chạm vào một mô hình ngôn ngữ mạnh, thông qua một giao diện đơn giản đến mức ai cũng hiểu cách dùng"
 },
 {
  "doc": "d1",
  "page": 10,
  "title": "LLM là gì? — một bộ não nền, không phải một chatbot",
  "key": [
   "llm",
   "não",
   "nền",
   "phải",
   "chatbot",
   "large",
   "language",
   "model",
   "hình",
   "ngôn",
   "ngữ",
   "rất",
   "lớn",
   "thường"
  ],
  "text": "LLM là gì? — một bộ não nền, không phải một chatbot | LLM (Large Language Model) là một mô hình ngôn ngữ rất lớn, | Chatbot | thường dựa trên kiến trúc Transformer, được luyện trên hàng | nghìn tỷ mảnh chữ để học cách đoán mảnh chữ tiếp theo trong H ngữ cảnh. AT Nhờ được luyện đủ rộng, nó trở thành một nền chung: thay vì mỗi việc train một model riêng, cùng một model làm được rất A nhiều việc. - H Chatbot chỉ là một dạng sản phẩm đóng gói quanh bộ não đó — N lớp áo bên ngoài. | 1 model nền | (LLM) | Tóm tắt tài liệu | ⟵ | Viết code | Dịch & phân tích | LLM = bộ não ngôn ngữ dùng chung cho mọi việc — sản phẩm bạn thấy chỉ là lớp áo bên ngoài | Model hiện nay chủ yếu là kiến trúc decoder-only (GPT, Claude, Gemini, Kimi), nhiều model dùng MoE; sau pre-training còn các bước căn chỉnh (SFT, RLHF/DPO) và luyện suy luận (reasoning training, từ ~2025)."
 },
 {
  "doc": "d1",
  "page": 11,
  "title": "Bên trong Transformer: đầu ra luôn là một phân bố xác suất",
  "key": [
   "bên",
   "transformer",
   "đầu",
   "luôn",
   "phân",
   "xác",
   "suất",
   "mọi",
   "ngữ",
   "cảnh",
   "model",
   "chấm",
   "điểm",
   "vựng"
  ],
  "text": "Bên trong Transformer: đầu ra luôn là một phân bố xác suất | Với mọi ngữ cảnh, model chấm điểm MỌI từ trong từ vựng — “land” 22%, “forest” 9%… — rồi chọn theo xác suất đó | Transformers, the tech behind LLMs - 3Blue1Brown"
 },
 {
  "doc": "d1",
  "page": 12,
  "title": "Sinh văn bản = đoán → nối vào câu → đoán tiếp",
  "key": [
   "sinh",
   "văn",
   "bản",
   "đoán",
   "nối",
   "vào",
   "câu",
   "tiếp",
   "mỗi",
   "token",
   "mới",
   "được",
   "ngữ",
   "cảnh"
  ],
  "text": "Sinh văn bản = đoán → nối vào câu → đoán tiếp | - Mỗi token mới được nối vào ngữ cảnh, rồi model chạy lại từ đầu — vòng lặp predict → append → rerun | Transformers, the tech behind LLMs - 3Blue1Brown"
 },
 {
  "doc": "d1",
  "page": 13,
  "title": "Token: model không đọc \"từ\", model đọc mảnh chữ",
  "key": [
   "token",
   "model",
   "đọc",
   "mảnh",
   "chữ",
   "nhìn",
   "nguyên",
   "vẹn",
   "cắt",
   "văn",
   "bản",
   "thành",
   "nhỏ",
   "gọi"
  ],
  "text": "Token: model không đọc \"từ\", model đọc mảnh chữ | Model không nhìn từ nguyên vẹn. Nó cắt văn bản | thành các mảnh nhỏ gọi là token: có từ là một mảnh, có từ vỡ ba bốn mảnh, cả dấu câu và khoảng trắng cũng là mảnh. | Ví dụ: \"Hello world\" ≈ 2 token, nhưng \"Xin chào\" có thể tới 3–4 token. | Tiếng Việt, code, JSON tốn token hơn tiếng Anh thường — vì dấu thanh, ký tự đặc biệt và cấu trúc bị | cắt nhỏ ra. | - | Mọi thứ model làm đều quy ra token — và mỗi token đều có giá. Nhớ điều này khi sang phần chi phí. | Thử trực tiếp: platform.openai.com/tokenizer · Số token chính xác phụ thuộc tokenizer của từng model."
 },
 {
  "doc": "d1",
  "page": 14,
  "title": "Context: bàn làm việc có hạn của model",
  "key": [
   "context",
   "bàn",
   "làm",
   "việc",
   "hạn",
   "model",
   "mỗi",
   "lần",
   "trả",
   "lời",
   "chỉ",
   "nhìn",
   "được",
   "lượng"
  ],
  "text": "Context: bàn làm việc có hạn của model | Mỗi lần trả lời, model chỉ nhìn được một lượng chữ có | hạn — gọi là context. Hãy hình dung một bàn làm việc: mọi thứ muốn model \"thấy\" phải bày lên bàn. | Quy đổi: 128K token ≈ một cuốn sách 300 trang; 1M token ≈ 4–5 cuốn sách trên bàn cùng lúc. | Bàn đầy quá thì đồ ở giữa bàn dễ bị bỏ sót — đặt điều | quan trọng ở giữa một prompt rất dài, model có thể | \"quên\" mất. | - | Context càng dài càng tốn tiền và càng chậm — bàn rộng không có nghĩa là dùng tốt | Hiện tượng “quên phần giữa”: Liu et al. (2023), “Lost in the Middle” — arxiv.org/abs/2307.03172. Model thế hệ mới đã cải thiện đáng kể nhưng chưa hết hẳn."
 },
 {
  "doc": "d1",
  "page": 15,
  "title": "Attention: mỗi từ được “nhìn sang” những từ quan trọng khác",
  "key": [
   "attention",
   "mỗi",
   "được",
   "nhìn",
   "sang",
   "quan",
   "trọng",
   "khác",
   "thay",
   "đọc",
   "tuần",
   "từng",
   "chữ",
   "chế"
  ],
  "text": "Attention: mỗi từ được “nhìn sang” những từ quan trọng khác | Thay vì đọc tuần tự từng chữ, cơ chế attention cho phép mỗi token: Chủ động “quay đầu” nhìn lại các token trước đó trong câu | Chấm điểm mức độ liên quan của từng token đối với nghĩa của mình Khóa nghĩa theo ngữ cảnh — “nó” là quyển sách hay cái túi, tùy theo nó chú ý vào từ nào | - Đây chính là chữ T trong GPT — và là lý do model hiểu ngữ cảnh tốt hơn hẳn các thế hệ trước Video minh họa: Attention in transformers, step-by-step - 3Blue1Brown"
 },
 {
  "doc": "d1",
  "page": 16,
  "title": "Hiểu attention để dùng AI hiệu quả: quản context = quản sự chú ý",
  "key": [
   "hiểu",
   "attention",
   "dùng",
   "hiệu",
   "quả",
   "quản",
   "context",
   "chú",
   "hạn",
   "điểm",
   "vậy",
   "cách",
   "bạn",
   "bày"
  ],
  "text": "Hiểu attention để dùng AI hiệu quả: quản context = quản sự chú ý | Attention có hạn và có \"điểm mù\". Vì vậy, cách bạn bày context quyết định model chú ý vào đâu: | 1 Đặt điều quan trọng đầu – cuối Đầu và cuối prompt được chú ý nhiều A nhất; đồ ở giữa dễ bị bỏ sót — yêu cầu quan trọng đừng chôn giữa. | 2 Giữ bàn làm việc sạch | Context rác = attention rác. Khi chat dài, tóm tắt lại thay vì kéo theo mọi thứ; khi vibe code, đưa đúng file liên quan, không dán cả repo. | 3 Cho tra sổ thay vì bắt nhớ | Tài liệu dài: lấy đoạn liên quan nhét vào context (RAG) thay vì trông chờ model nhớ hết hoặc nhét cả cuốn. | - Agent mạnh không phải vì context khổng lồ — mà vì nó có tools để lấy đúng thứ vào bàn làm việc đúng lúc"
 },
 {
  "doc": "d1",
  "page": 17,
  "title": "Tham số (parameter): những \"khớp nối\" model học được",
  "key": [
   "tham",
   "parameter",
   "khớp",
   "nối",
   "model",
   "học",
   "được",
   "sau",
   "luyện",
   "xong",
   "biết",
   "nằm",
   "con",
   "định"
  ],
  "text": "Tham số (parameter): những \"khớp nối\" model học được | Sau khi luyện xong, những gì model \"biết\" nằm trong các con số cố định bên trong gọi là tham số — hãy hình dung | như khớp nối thần kinh: luyện càng kỹ, các khớp nối càng được siết đúng. | Tham số không phải thứ bạn chỉnh khi dùng model — nó được đóng gói sẵn trong \"bộ não\" (file weights). Bạn chỉ chỉnh được context và các núm vặn lúc gọi (như temperature). | 2020 — GPT-3 175 tỷ - 2.800 tỷ một \"bác sĩ đa năng\" — mọi token đều đi qua toàn bộ khớp nối T (dense) | 2026 — Kimi K3 | một \"bệnh viện đa khoa\" — mỗi token chỉ gọi vài chuyên gia (MoE) | test loss ↓ | Nhiều tham số ≠ tốn hơn tuyến tính — nhờ MoE, bệnh viện lớn gấp 16 lần | mà chi phí mỗi ca khám gần như không đổi | compute / dữ liệu (thang log) → | Luật chơi 2020–2024: cứ thêm compute + dữ liệu là model khôn lên một cách dự đoán được (scaling law, Kaplan et al. 2020) | MoE: Shazeer et al. (2017) — arxiv.org/abs/1701.06538 · Kimi K3 (16/7/2026): ~2.8 nghìn tỷ tham số MoE — k3-kimi.com"
 },
 {
  "doc": "d1",
  "page": 18,
  "title": "LLM được tạo ra như thế nào? — đọc nhiều, được chỉ, được uốn nắn, luyện đề",
  "key": [
   "llm",
   "được",
   "tạo",
   "thế",
   "nào",
   "đọc",
   "nhiều",
   "chỉ",
   "uốn",
   "nắn",
   "luyện",
   "pre",
   "training",
   "thư"
  ],
  "text": "LLM được tạo ra như thế nào? — đọc nhiều, được chỉ, được uốn nắn, luyện đề | - ① Pre-training — \"đọc cả thư viện\": học tiếng nói và kiến thức từ hàng nghìn tỷ token. ② SFT — \"được chỉ cách trả A lời\": học theo ví dụ mẫu để ra dáng trợ lý. ③ RLHF/DPO — \"được uốn nắn\": học theo phản hồi con người, an toàn và dễ chịu hơn. ④ Luyện suy luận — \"giải đề tự chấm\" (từ ~2025): luyện toán/code có đáp án kiểm chứng được → model biết làm nháp trước khi trả lời. | Đọc vạn cuốn sách chưa chắc biết trả lời phỏng vấn — đó là lý do cần bước ②, ③, ④ | Ouyang et al. (2022), InstructGPT — arxiv.org/abs/2203.02155 · Rafailov et al. (2023), DPO — arxiv.org/abs/2305.18290 · RLVR: RL with verifiable rewards."
 },
 {
  "doc": "d1",
  "page": 19,
  "title": "RLHF: ba bước uốn cỗ máy đoán token thành trợ lý biết nghe lời",
  "key": [
   "rlhf",
   "bước",
   "uốn",
   "máy",
   "đoán",
   "token",
   "thành",
   "trợ",
   "biết",
   "nghe",
   "lời",
   "model",
   "viết",
   "nhiều"
  ],
  "text": "RLHF: ba bước uốn cỗ máy đoán token thành trợ lý biết nghe lời | ① Model viết nhiều câu trả lời «Cùng một câu hỏi» ↓ LLM | Trả lời A Trả lời C | Trả lời B Trả lời D | AI IN | ② Người chấm xếp hạng | ③ Huấn luyện theo điểm | Trả lời B | 1 | Trả lời D | 2 | K AT Trả lời A | 3 | Trả lời C | 4 | - H ↓ NREWARD MODEL máy chấm điểm thay người | tăng xác suất câu ghi điểm cao | LLM ↓ | câu trả lời vừa viết | ↓ điểm: 9.2 / 10 | lặp lại hàng nghìn lần → model dần “biết nghe lời” | Cỗ máy đoán token + điểm xếp hạng của con người → trợ lý helpful · harmless · honest | Ouyang et al. (2022), “Training language models to follow instructions with human feedback” (InstructGPT) — arxiv.org/abs/2203.02155 · DPO (cách đơn giản hơn, 2023) — arxiv.org/abs/2305.18290"
 },
 {
  "doc": "d1",
  "page": 20,
  "title": "Giới hạn bẩm sinh: học giả trong bong bóng",
  "key": [
   "giới",
   "hạn",
   "bẩm",
   "sinh",
   "học",
   "giả",
   "bong",
   "bóng",
   "thời",
   "gian",
   "nói",
   "chắc",
   "đúng",
   "rồi"
  ],
  "text": "Giới hạn bẩm sinh: học giả trong bong bóng | Bong bóng thời gian | Nói chắc như đúng rồi | Bàn làm việc có hạn | Model bị \"đóng băng\" tại ngày ngừng đọc. | N Chuyện sau đó nó không biết — trừ khi O bạn cung cấp thêm (knowledge cutoff). | Model tối ưu cho câu nghe hợp lý, không phải tra sự thật — nên có thể tự tin mà sai (hallucination). | Context có trần; quá dài vừa tốn tiền vừa dễ bỏ sót thông tin ở giữa. | - AT H \"Why does it work? We don't know — a lot here are intuitions, not theorems or truths.\" — Łukasz Kaiser, đồng tác giả N \"Attention Is All You Need\" (OpenAI) Đây không phải lỗi tạm thời — đó là bản chất của cỗ máy đoán token. Vì vậy ta cần prompt tốt, context sạch, tra | sổ (RAG), tools, và luôn kiểm chứng. | “Biết nhiều” khác “làm được”: dữ liệu mới và hành động thật cần tools/retrieval/workflow — nền của các ngày sau."
 },
 {
  "doc": "d1",
  "page": 21,
  "title": "Vì sao model vẫn sai: nó rất giỏi học vẹt đường tắt",
  "key": [
   "sao",
   "model",
   "vẫn",
   "sai",
   "rất",
   "giỏi",
   "học",
   "vẹt",
   "đường",
   "tắt",
   "phân",
   "loại",
   "spam",
   "câu"
  ],
  "text": "Vì sao model vẫn sai: nó rất giỏi học vẹt đường tắt | 1 Phân loại spam | 2 Câu chủ quan vs khách quan | 3 Suy luận ngôn ngữ (MNLI) | Model thực chất đã học: | N “đếm số hyperlink trong email” Email sạch nhưng nhiều link → vẫn bị gán AT spam | Model thực chất đã học: | “có phải câu trích từ film review không” | Ăn gian bằng nguồn gốc câu, không phải nội dung câu | Model thực chất đã học: | “câu có động từ phủ định” | Đổi cấu trúc dữ liệu test là điểm tụt ngay | - Ba “đường tắt” (spurious cues) trên do chính LLM tự động phát hiện và mô tả bằng ngôn ngữ tự nhiên — trên quy mô 675 bài toán | thật của benchmark OpenD5. | Benchmark cao ≠ model hiểu đúng thứ bạn tưởng — luôn test trên dữ liệu của chính mình | Zhong, Snell, Klein & Steinhardt (2022), “Describing Differences between Text Distributions with Natural Language”, ICML 2022 · Zhong et al. (2023), “Goal Driven Discovery of Distributional Differences via Language Descriptions” (OpenD5), NeurIPS 2023"
 },
 {
  "doc": "d1",
  "page": 22,
  "title": "Chain-of-Thought: chỉ thêm \"giấy nháp\", từ sai thành đúng",
  "key": [
   "chain",
   "thought",
   "chỉ",
   "thêm",
   "giấy",
   "nháp",
   "sai",
   "thành",
   "đúng",
   "bài",
   "toán",
   "quả",
   "bóng",
   "tennis"
  ],
  "text": "Chain-of-Thought: chỉ thêm \"giấy nháp\", từ sai thành đúng | Bài toán: \"Có 5 quả bóng tennis. Mua thêm 2 hộp, mỗi hộp 3 quả. Hỏi tổng cộng có bao nhiêu quả?\" | N Không có nháp — trả lời ngay O Model đọc câu hỏi → bật ra đáp án ngay: \"Đáp án là 27 quả.\" ✗ SAI | Có giấy nháp — \"hãy nghĩ từng bước\" | \"Bắt đầu có 5 quả. Mỗi hộp 3 quả × 2 hộp = 6 quả. 5 + 6 = 11. Đáp án là 11 quả.\" | ✓ ĐÚNG | - ùng một model, cùng một câu hỏi — cho nó được viết nháp từng bước, bản chất suy luận lộ ra | Wei et al. (2022), “Chain-of-Thought Prompting Elicits Reasoning in Large Language Models” — arxiv.org/abs/2201.11903 · Đây là mầm của các reasoning model (o1, R1...) và của test-time compute ở các slide sau."
 },
 {
  "doc": "d1",
  "page": 23,
  "title": "Từ LLM đến agent: bốn mức độ — mỗi bậc thêm một năng lực",
  "key": [
   "llm",
   "đến",
   "agent",
   "bốn",
   "mức",
   "mỗi",
   "bậc",
   "thêm",
   "năng",
   "lực",
   "level",
   "não",
   "suy",
   "luận"
  ],
  "text": "Từ LLM đến agent: bốn mức độ — mỗi bậc thêm một năng lực | LEVEL 0 | Bộ não suy luận | LLM trần — không công cụ, không dữ liệu mới | mức tự chủ & tác động thật tăng dần → | - H AC LEVEL1 ó kết nối | + tools: search web, đọc | I Ndatabase, gọi API — vượt khỏi | LEVEL 2 | Biết lập kế hoạch | + tự chia mục tiêu thành nhiều bước, dùng nhiều tool nối tiếp, tự kiểm tra kết quả từng bước | LEVEL 3 | Đội agent phối hợp | + nhiều agent chuyên biệt chia việc như một đội ngũ (multiagent) | bong bóng thời gian | Agent không phải “một loại model khác” — đó là LLM được đặt vào vòng làm việc có mục tiêu và hành động"
 },
 {
  "doc": "d1",
  "page": 24,
  "title": "Giải phẫu một agent: 5 bộ phận là một vòng lặp",
  "key": [
   "giải",
   "phẫu",
   "agent",
   "phận",
   "vòng",
   "lặp",
   "goal",
   "memory",
   "tay",
   "ghi",
   "nhớ",
   "bước",
   "mục",
   "tiêu"
  ],
  "text": "Giải phẫu một agent: 5 bộ phận là một vòng lặp | ① Goal | Memory AT sổ tay ghi nhớ các bước | mục tiêu cần đạt ghi / đọc | ② Reasoning | bộ não LLM chia bước | N - vòng lặp agent | C Tquan sát kết quả → lặp lại | ④ Action hành động ra đời thật | ③ Tools | search · API · database · code | Agent = Goal + Reasoning + Tools + Memory + Action — chạy thành vòng lặp cho tới khi xong việc"
 },
 {
  "doc": "d1",
  "page": 25,
  "title": "Cùng một mức năng lực, giá rơi khoảng 10 lần mỗi năm",
  "key": [
   "mức",
   "năng",
   "lực",
   "giá",
   "rơi",
   "khoảng",
   "lần",
   "mỗi",
   "năm",
   "việc",
   "ngoái",
   "phải",
   "dùng",
   "model"
  ],
  "text": "Cùng một mức năng lực, giá rơi khoảng 10 lần mỗi năm | Việc năm ngoái phải dùng model đắt nhất — năm nay model rẻ đã làm được | Tổng hợp từ bảng giá các nhà cung cấp, 2023–2026."
 },
 {
  "doc": "d1",
  "page": 26,
  "title": "Chọn model theo TẦNG, không chọn theo tên",
  "key": [
   "chọn",
   "model",
   "theo",
   "tầng",
   "tên",
   "việc",
   "bạn",
   "đơn",
   "giản",
   "khối",
   "lượng",
   "lớn",
   "phân",
   "loại"
  ],
  "text": "Chọn model theo TẦNG, không chọn theo tên | VIỆ ỦA BẠ ẦNG MODEL | Việc đơn giản, khối lượng lớn | phân loại · trích xuất · tóm tắt ngắn | Việc hàng ngày | viết · code · phân tích công việc · automation | Việc khó nhất | N suy luận nhiều bước · code phức tạp · tài liệu dài · độ | tin cậy cao | Việc cần kiểm soát A dữ liệu nhạy cảm · chi phí ở quy mô lớn Hai lỗi đối xứng: | ✗ việc đơn giản mà gọi frontier → phí tiền ✗ việc khó mà cố dùng rẻ → kết quả tệ | - | TẦNG 1 — FRONTIER ĐÓNG Fable 5 · GPT-5.6 Sol · Opus 4.8 đắt nhất — chỉ trả cho việc thật sự khó | ★ MẶC ĐỊNH THỬ TẦNG NÀY TRƯỚ ẦNG 2 — RẺ MÀ MẠNH Sonnet 4.6 · Terra · Gemini 3.1 Pro · Kimi K3 · Haiku · Flash | giải quyết đa số việc hằng ngày | TẦNG 3 — SELF-HOST / SIÊU RẺ Kimi K3 open-weight · DeepSeek · Qwen khi cần kiểm soát dữ liệu hoặc chi phí quy mô lớn | Bắt đầu từ model đủ tốt và đủ rẻ — chỉ nâng tầng khi kết quả thực sự chặn use case"
 },
 {
  "doc": "d1",
  "page": 27,
  "title": "Token có giá: vé vào rẻ, vé ra đắt gấp 3–5 lần",
  "key": [
   "token",
   "giá",
   "vào",
   "đắt",
   "gấp",
   "lần",
   "hóa",
   "đơn",
   "gọi",
   "api",
   "input",
   "output",
   "chữ",
   "bạn"
  ],
  "text": "Token có giá: vé vào rẻ, vé ra đắt gấp 3–5 lần | HÓA ĐƠN — 1 LẦN GỌI API | VÉ VÀO — INPUT | VÉ RA — OUTPUT | ×1 ×3–5 AT chữ BẠN gửi đi: | K prompt · system instruction · C context · lịch sử chat N - rẻ — model chỉ cần đọc | chữ MODEL viết ra — nó phải tự sinh từng mảnh một, vừa chậm vừa tốn | đắt — model phải “vắt óc” | input 1.150 tok × $3 / 1M output 200 tok × $15 / 1M | $0.00345 $0.00300 | TỔNG | ≈ $0.0065 | số liệu ví dụ — giá thật tùy model & nhà cung cấp | Đọc mục usage trong mỗi response — đó là hóa đơn chi tiết A giúp bạn kiểm soát chi phí từ ngày đầu. Input tokens + Output tokens = Chi phí mỗi lần gọi — kiểm soát output là núm vặn lớn | nhất"
 },
 {
  "doc": "d1",
  "page": 28,
  "title": "Giải phẫu một prompt: bốn lớp xếp chồng",
  "key": [
   "giải",
   "phẫu",
   "prompt",
   "bốn",
   "lớp",
   "xếp",
   "chồng",
   "phần",
   "system",
   "instruction",
   "lời",
   "dặn",
   "đầu",
   "model"
  ],
  "text": "Giải phẫu một prompt: bốn lớp xếp chồng | 1 PROMPT = 4 PHẦN | AI | LỚP 1 | System instruction | “Lời dặn đầu ca”: model là ai, cư xử thế nào, không được làm gì | «Bạn là trợ lý y khoa, trả lời ngắn gọn, không chẩn đoán…» | LỚP 2 A User input | Câu hỏi / yêu cầu của người dùng trong lượt này | «Tóm tắt báo cáo Q1 giúp mình» | LỚP 3 - Context bổ N sung | Tài liệu, lịch sử chat, dữ liệu tra sổ — phần bày lên “bàn làm việc” | «[đính kèm: bao_cao_q1.pdf — 3 đoạn liên quan]» | LỚP 4 A Output mong I Nmuốn | Dạng kết quả: gạch đầu dòng? bảng? JSON? dài bao nhiêu? | «3 bullet + 1 rủi ro chính, tiếng Việt» | Viết rõ cả 4 lớp = đã làm tốt một nửa “prompt engineering” — phần còn lại là các ngày sau"
 },
 {
  "doc": "d1",
  "page": 29,
  "title": "Hai núm vặn chọn từ: temperature & top_p",
  "key": [
   "hai",
   "núm",
   "vặn",
   "chọn",
   "temperature",
   "top",
   "liều",
   "câu",
   "tách",
   "bảng",
   "xác",
   "suất",
   "đổi",
   "theo"
  ],
  "text": "Hai núm vặn chọn từ: temperature & top_p | temperature — “núm vặn độ liều” | Cùng một câu: “Một tách ___” — bảng xác suất đổi theo =0 | cà phê | trà | mưa | sao | luôn chọn từ chắc nhất → ổn định, lặp lại, hợp code & phân tích | T=1 T=2 | cà phê cà phê | cân bằng tự nhiên — | vẫn ưu tiên từ hợp lý | trà | mưa | sao | trà | mưa | sao | phân bố phẳng ra → đa dạng, “phiêu”, dễ lạc đề | - | top_p — “chỉ xem top đầu bảng” (p = 0.9) | ① Bảng xác suất gốc | ② Bảng mới | →N giữ nhóm cộng dồn ≥ 90% | cắt & chuẩn hóa lại | cà phê trà | mưa | sao | cà phê trà mưa | “sao” (đuôi dài xác suất thấp) bị loại khỏi lựa chọn — model chỉ còn chọn | trong nhóm đáng tin. Thường chỉ vặn một trong hai: temperature hoặc top_p. | Lưu ý quan trọng: hai núm này không làm model thông minh hơn — chỉ đổi cách chọn từ, không thêm tri thức. | Mặc định an toàn: temperature = 0 cho việc cần ổn định — chỉ tăng khi thật sự cần đa dạng"
 },
 {
  "doc": "d2",
  "page": 1,
  "title": "Xác định bài toán cho AI",
  "key": [
   "xác",
   "định",
   "bài",
   "toán",
   "yêu",
   "cầu",
   "đến",
   "problem",
   "statement",
   "ràng"
  ],
  "text": "Xác định bài toán cho AI — Từ yêu cầu mơ hồ đến Problem Statement rõ ràng."
 },
 {
  "doc": "d2",
  "page": 2,
  "title": "Agenda",
  "key": [
   "agenda",
   "mục",
   "tiêu",
   "biến",
   "yêu",
   "cầu",
   "thành",
   "problem",
   "statement",
   "ràng",
   "quyết",
   "định",
   "sáng",
   "khung"
  ],
  "text": "Agenda | — Mục tiêu: Biến yêu cầu mơ hồ thành Problem Statement rõ ràng để ra quyết định | SÁNG | KHUNG LÝ THUYẾT (4H) | · Problem Discovery (Double Diamond, HCD) · Problem Statement & định lượng hóa · PAIR ① AI có thêm giá trị? · PAIR ② Automate/Augment → Rule/Workflow/Agent · PAIR ③ Reward function & success criteria · Khi AI sai & UX/HITL · PS hoàn chỉnh → Go/Not Yet/No-Go | AI IN | CHIỀU | BÀ ỘP | THỰ ÀNH LAB (4H) | · Cá nhân: Tìm 5 bài toán & điền 3 Problem H Cards T · Nhóm: Phản biện chéo, chốt 1 bài toán · Nhóm: Xác thực dữ liệu & vẽ quy trình C · Nhóm: Xác định giải pháp & ra quyết định - · Cá nhân: Viết nhật ký phản tư (Reflection Log) | CUỐI BUỔI | · Nhật ký tìm và lọc bài toán (Cá nhân) · Problem Statement hoàn chỉnh (Nhóm) · Nhật ký phản tư (Cá nhân) | MỞ ĐẦU · AGENDA | DAY 02 · 04 / 83"
 },
 {
  "doc": "d2",
  "page": 3,
  "title": "Tìm đúng vấn đề trước khi tìm giải pháp",
  "key": [
   "tìm",
   "đúng",
   "vấn",
   "trước",
   "giải",
   "pháp",
   "hình",
   "double",
   "diamond",
   "don",
   "norman",
   "british",
   "design",
   "council"
  ],
  "text": "Tìm đúng vấn đề trước khi tìm giải pháp | — Mô hình Double Diamond — Don Norman / British Design Council (2005) | AI | IN | DIAMOND 1 — TÌM ĐÚNG VẤN ĐỀ | Discover: Mở rộng — khảo sát vấn đề căn bản. | N Define: Thu hẹp — xác định đúng bài toán gốc. AT D M D 2 — T Ì M Đ Ú N G G I Ả I P H Á P A Develop: Mở rộng — nhiều giải pháp tiềm năng. H Deliver: Thu hẹp — chọn và triển khai. -\"Kỹ sư và doanh nhân được đào tạo để giải vấn đề. Nhà thiết kế được đào A tạo để khám phá vấn đề thật.\" | Giải pháp xuất sắc cho sai vấn đề có thể còn tệ hơn không có giải pháp. | NGUỒN Don Norman — jnd.org · Design Council — The Double Diamond BÀI TOÁN · DOUBLE DIAMOND | DAY 02 · 16 / 83"
 },
 {
  "doc": "d2",
  "page": 4,
  "title": "Diamond 1 — Tìm đúng vấn đề",
  "key": [
   "diamond",
   "tìm",
   "đúng",
   "vấn",
   "phân",
   "thấu",
   "hiểu",
   "sâu",
   "sắc",
   "hội",
   "lựa",
   "chọn",
   "chính",
   "xác"
  ],
  "text": "Diamond 1 — Tìm đúng vấn đề | — Phân kỳ để thấu hiểu sâu sắc, hội tụ để lựa chọn chính xác | DISCOVER · PHÂ Ỳ | Khám phá / mở rộng góc nhìn | · Quan sát thực tế (Observation) · Phỏng vấn người dùng (User Interview) · Khảo sát (Survey) · Nhật ký hành vi (Diary Study) · Phân tích dữ liệu / Nhật ký hệ thống | · Bản đồ các bên liên quan (Stakeholder Mapping) | - DEFINE · HỘ Ụ Định nghĩa / chọn lọc dựa vào dữ liệu | · Sơ đồ đồng cảm / Gom nhóm (Affinity Mapping) · Kỹ thuật đặt câu hỏi 5 Whys · Ma trận Tác động – Nỗ lực (Impact-Effort) · Biểu quyết bằng chấm tròn (Dot Voting) · Câu hỏi mở hướng giải quyết (How Might We) · Phát biểu bài toán (Problem Statement) | BÀI TOÁN · DIAMOND 1 | DAY 02 · 17 / 83"
 },
 {
  "doc": "d2",
  "page": 5,
  "title": "Khởi nguồn từ bài toán, không bắt đầu từ AI",
  "key": [
   "khởi",
   "nguồn",
   "bài",
   "toán",
   "bắt",
   "đầu",
   "học",
   "thực",
   "hiểu",
   "lĩnh",
   "vực",
   "quy",
   "thị",
   "trường"
  ],
  "text": "Khởi nguồn từ bài toán, không bắt đầu từ AI | — Ba bài học thực tế về am hiểu lĩnh vực, quy mô thị trường và định vị giải pháp | CURSOR | A R FA | NOTEBOOKLM | \"Lệch năng lực cốt lõi\" | ừ bỏ mảng AI thiết kế cơ khí (CAD) để H tập trung vào AI code editor — nơi đội K AT ngũ am hiểu sâu sắc quy trình nghiệp vụ. | \"Sản phẩm tốt ≠ Thị trường lớn\" | Ứng dụng đọc tin tích hợp AI xuất sắc, nhưng quy mô thị trường quá hẹp để thương mại hóa thành công (đóng cửa 1/2024). | \"Định vị đúng điểm đau\" | Tập trung giải quyết nhu cầu hỏi đáp, tóm tắt trên tài liệu cá nhân và đối chiếu nguồn gốc bằng trích dẫn. | - Lộ trình: Bài toán → Quy trình vận hành → Chỉ số đo lường → Giải pháp AI | NGUỒN Lenny's Podcast — The rise of Cursor · The Verge — Artifact · Google Blog — NotebookLM BÀI TOÁN · CASE STUDY | DAY 02 · 22 / 83"
 },
 {
  "doc": "d2",
  "page": 6,
  "title": "Tìm bài toán AI ở đâu?",
  "key": [
   "tìm",
   "bài",
   "toán",
   "đâu",
   "bắt",
   "đầu",
   "việc",
   "quan",
   "sát",
   "hoạt",
   "động",
   "thực",
   "xung",
   "quanh"
  ],
  "text": "Tìm bài toán AI ở đâu? | — Bắt đầu từ việc quan sát các hoạt động thực tế xung quanh | REPETITIVE | Tác vụ lặp lại | Việc diễn ra thường xuyên; công đoạn nào cần chuẩn hóa để hướng tới tự động hóa? | AI | TIME-CONSUMING | N Tiêu tốn thời gian Khối lượng xử lý lớn; thời gian T hao phí ở bước nào (tìm kiếm, A đọc hiểu, chờ đợi, định dạng)? | AI ADVANTAGE | Lợi thế của AI | Tác vụ đòi hỏi phân tích ngữ cảnh, xử lý ngôn ngữ tự nhiên, tổng hợp đa nguồn. | USER PAIN POINTS | Điểm đau người dùng | Ai đang gặp khó khăn, phàn nàn hoặc bị tắc nghẽn liên tục? | - ập trung nhận diện vấn đề; chưa vội đề xuất giải pháp. Sàng lọc bài toán sẽ diễn ra vào buổi chiều. | BÀI TOÁN · 4 LENSES | DAY 02 · 23 / 83"
 },
 {
  "doc": "d2",
  "page": 7,
  "title": "Sai lầm thường gặp — Anti-patterns",
  "key": [
   "sai",
   "lầm",
   "thường",
   "gặp",
   "anti",
   "patterns",
   "dấu",
   "hiệu",
   "cảnh",
   "báo",
   "bài",
   "toán",
   "chưa",
   "được"
  ],
  "text": "Sai lầm thường gặp — Anti-patterns | — Dấu hiệu cảnh báo bài toán chưa được định hình rõ hoặc giải pháp AI được lựa chọn quá sớm | Ưu tiên giải pháp (Solution-first) | Mơ hồ hiện trạng (No baseline) | N Xây dựng chatbot/agent trước khi làm rõ quy trình vận hành và điểm O nghẽn thực tế. | Không lượng hóa tổn thất hiện tại, dẫn đến mất căn cứ đánh giá hiệu quả cải tiến. | AT H Bỏ qua đánh giá (No evaluation) - Không thiết lập kịch bản kiểm thử, chỉ số đo lường hoặc phương án đối N chứng. | Mập mờ ranh giới (No boundary) | Không rõ phạm vi tự chủ của AI và thời điểm cần con người phê duyệt (Human-in-the-loop). | ếu phát hiện mắc các sai lầm trên, hãy quay lại làm rõ Problem Statement trước khi chọn công nghệ. | BÀI TOÁN · ANTI-PATTERNS | DAY 02 · 24 / 83"
 },
 {
  "doc": "d2",
  "page": 8,
  "title": "PAIR · CHƯƠNG 1 — REFRAME CÂU HỎI",
  "key": [
   "pair",
   "chương",
   "reframe",
   "câu",
   "hỏi",
   "can",
   "use",
   "thay",
   "bằng",
   "hai",
   "how",
   "might",
   "solve",
   "this"
  ],
  "text": "PAIR · CHƯƠNG 1 — REFRAME CÂU HỎI | \"Can we use AI to ______?\" | ↓ thay bằng hai câu hỏi: ↓ | AT H \"How might we A solve ______?\" | \"Can AI solve this problem in a unique way?\" | - ỏi về bài toán trước, về AI sau — AI chỉ là một phương án trong nhiều phương án khả dĩ. âu hỏi đúng quyết định bài toán bạn giải — và giải pháp bạn chọn. | NGUỒN Google PAIR — Ch.1 User Needs + Defining Success BÀI TOÁN · PAIR REFRAME | DAY 02 · 26 / 83"
 },
 {
  "doc": "d2",
  "page": 9,
  "title": "Quick Problem Card",
  "key": [
   "quick",
   "problem",
   "card",
   "khung",
   "định",
   "hình",
   "bài",
   "toán",
   "câu",
   "đối",
   "tượng",
   "ảnh",
   "hưởng",
   "actor"
  ],
  "text": "Quick Problem Card | — Khung định hình bài toán | Bài toán (1 câu) problem Đối tượng ảnh hưởng actor Quy trình hiện tại workflow Nút thắt & Tác động bottleneck + impact Chỉ số đo thành công success metric Định hướng giải pháp direction | AI IN | Vấn đề cụ thể cần giải quyết (không bao gồm giải pháp). Cá nhân hoặc bộ phận chịu tác động trực tiếp từ vấn đề. | ác bước vận hành thủ công hoặc tự động hiện tại (gồm 3–7 bước). AT H Khâu gây chậm trễ, sai sót hoặc lặp lại; hệ quả hay tổn thất cụ thể. Chỉ số định lượng cụ thể dùng để chứng minh hiệu quả cải tiến. - No AI / Rule / Workflow / Agent / Chưa xác định. | PROBLEM STATEMENT · QUICK CARD | DAY 02 · 28 / 83"
 },
 {
  "doc": "d2",
  "page": 10,
  "title": "Câu hỏi khai thác bài toán",
  "key": [
   "câu",
   "hỏi",
   "khai",
   "thác",
   "bài",
   "toán",
   "định",
   "hình",
   "vấn",
   "dành",
   "bên",
   "liên",
   "quan",
   "chính"
  ],
  "text": "Câu hỏi khai thác bài toán | — Bộ câu hỏi định hình vấn đề dành cho các bên liên quan hoặc chính mình | BỘ THẺ CÂU HỎI #3 — CẤU TRÚC PS | 01 | Quy trình hiện tại như thế nào? | Công cụ, các bước, cơ chế bàn giao thông tin? | 03 | Hao phí hiện tại là bao nhiêu? | Thời gian, chi phí nhân sự, SLA, cơ hội bỏ lỡ? | 05 ậu quả khi xảy ra sai sót? Phạm vi tự quyết của AI; điểm cần con người phê duyệt? | 02 | - Nút thắt nằm ở đâu? Bước nào chậm, dễ sai sót, lặp lại? | 04 | Tiêu chí thành công đo bằng gì? | Hiệu quả cải tiến định lượng cụ thể? | 06 | Có giải pháp phi AI đơn giản hơn? | Quy tắc, checklist, quy trình hay tài liệu hướng dẫn? | PROBLEM STATEMENT · 6 CÂU HỎI | DAY 02 · 30 / 83"
 },
 {
  "doc": "d2",
  "page": 11,
  "title": "Định lượng hóa bài toán",
  "key": [
   "định",
   "lượng",
   "hóa",
   "bài",
   "toán",
   "điểm",
   "đau",
   "chưa",
   "được",
   "thể",
   "xác",
   "giá",
   "trị",
   "thực"
  ],
  "text": "Định lượng hóa bài toán | — Điểm đau chưa được định lượng thì không thể xác định giá trị thực tế của AI | 01 · BASELINE | 02 · TARGET | 03 · MEASUREMENT | N Hiện trạng / where we are O Mức hao phí hiện tại là bao nhiêu? Bằng con số cụ thể. | Mục tiêu / where to go | Kỳ vọng cải thiện ở mức độ nào? Ngưỡng cụ thể là gì? | Đo lường / how we know | Chỉ số nào chứng minh tính hiệu quả? Cách thu thập? | VÍ DỤ N - Ờ I G À À Rút ngắn từ 90 phút xuống dưới 30 phút. | CHẤT LƯỢNG CÔNG VIỆC | Giảm tỷ lệ lỗi phân loại từ 20% xuống dưới 5%. | TẢI TRỌNG VẬ ÀNH | Cắt giảm 40% câu hỏi trùng lặp cần Trợ giảng xử lý. | PROBLEM STATEMENT · ĐỊNH LƯỢNG | DAY 02 · 31 / 83"
 },
 {
  "doc": "d2",
  "page": 12,
  "title": "Thiết lập chỉ số: Output & Input",
  "key": [
   "thiết",
   "lập",
   "chỉ",
   "output",
   "input",
   "lường",
   "cần",
   "phản",
   "ánh",
   "kết",
   "quả",
   "cuối",
   "đòn",
   "bẩy"
  ],
  "text": "Thiết lập chỉ số: Output & Input | — Chỉ số đo lường cần phản ánh kết quả cuối và các đòn bẩy có thể tác động | OUTPUT METRIC | INPUT METRICS | Kết quả cuối cùng / what we optimize | N · Thời lượng hoàn tất quy trình giảm bao nhiêu? · Tỷ lệ sai sót / chất lượng đầu ra thay đổi thế nào? AT · Giá trị thực tế người dùng nhận được rõ nét hơn? | tăng cái này → đo cái kia | Các đòn bẩy / what we can move | · Tỷ lệ câu hỏi được phân loại chính xác. · Tỷ lệ yêu cầu được chuyển tiếp hỗ trợ kịp thời. · Thời gian Trợ giảng hiệu chỉnh bản nháp phản hồi. | - \"Nâng cao hiệu suất\" không phải chỉ số — cần gắn với hiện trạng, mục tiêu và phương pháp đo. | NGUỒN Amplitude — North Star Playbook · Lenny Rachitsky — Choosing Your North Star Metric PROBLEM STATEMENT · METRICS | DAY 02 · 32 / 83"
 },
 {
  "doc": "d2",
  "page": 13,
  "title": "Ba bước quyết định AI theo PAIR",
  "key": [
   "bước",
   "quyết",
   "định",
   "theo",
   "pair",
   "google",
   "people",
   "guidebook",
   "chương",
   "user",
   "needs",
   "defining",
   "success",
   "giao"
  ],
  "text": "Ba bước quyết định AI theo PAIR | — Google People + AI Guidebook · Chương 1: User Needs + Defining Success | BƯỚC ① | BƯỚC ② | BƯỚC ③ | Giao điểm: nhu cầu × thế mạnh | AI H Bài toán của bạn có nằm trong nhóm việc AT AI làm tốt hơn hẳn rule/heuristic không? VD: câu hỏi trùng lặp của 1000 học viên K3 & A K4 có nằm trong thế mạnh của AI? | Automate hay Augment? | AI thay thế hay hỗ trợ con người? Mức tự động hóa tăng dần theo độ tin cậy và rủi ro. | VD: AI trả lời thay TA luôn, hay chỉ soạn nháp để TA duyệt? | N - H → trả lời câu hỏi 1: có thực sự cần AI? | → trả lời câu hỏi 2: giải pháp ở cấp độ nào? | Reward function & tiêu chí thành công | Định nghĩa \"đúng/sai\" của hệ thống (precision ↔ recall) và ngưỡng thành công đo được. | VD: đo bằng gì — thời gian phản hồi? tỷ lệ định hướng sai? | → trả lời câu hỏi 3: PS đã đủ rõ để đo? | Ánh xạ về 4 câu hỏi trọng tâm của ngày: ① Có cần AI? · ② Cấp độ nào? · ③ Đủ rõ để đo? · Tổng hợp ①②③ → ④ Go / Not Yet / No-Go | Đi hết 3 bước này, bạn trả lời được cả 4 câu hỏi của ngày hôm nay — từ \"có thực sự cần AI?\" đến \"Go, Not Yet hay NoA I Go\". | NGUỒN Google PAIR — People + AI Guidebook · PAIR — Ch.1 User Needs + Defining Success CÓ NÊN ỨNG DỤNG AI · PAIR 3 BƯỚC | DAY 02 · 35 / 83"
 },
 {
  "doc": "d2",
  "page": 14,
  "title": "Khi nào AI có lợi thế?",
  "key": [
   "nào",
   "lợi",
   "thế",
   "tám",
   "trường",
   "hợp",
   "pair",
   "gọi",
   "probably",
   "better",
   "chương",
   "gợi",
   "theo",
   "từng"
  ],
  "text": "Khi nào AI có lợi thế? | — Tám trường hợp PAIR gọi là \"AI probably better\" · Chương 1 | PAIR ① ② ③ | Gợi ý theo từng người · recommendation | Mỗi người dùng nhận một nội dung gợi ý khác nhau. | Cá nhân hóa · personalization | Trải nghiệm tự điều chỉnh theo từng người, ngày càng hợp hơn. | Nhận diện cả một lớp thực thể | N Nhận ra mọi đối tượng cùng loại — VD mọi khuôn mặt. Agent/bot cho một lĩnh vực cụ thể Trợ lý ảo xử lý trọn một phạm vi việc chuyên biệt. | Dự đoán tương lai · prediction | - Đoán trước sự kiện sắp xảy ra để chuẩn bị phản ứng. Hiểu ngôn ngữ tự nhiên · natural language Hiểu câu hỏi viết tự do bằng lời nói hằng ngày. | Phát hiện cái hiếm & biến đổi | Bắt sự kiện hiếm, thay đổi theo thời gian — VD gian lận. | Nội dung động thay giao diện tĩnh | Nội dung linh hoạt hiệu quả hơn layout cố định, dễ đoán. | AI chỉ đáng làm khi bài toán nằm trong nhóm này. | NGUỒN PAIR — Ch.1 User Needs + Defining Success CÓ NÊN ỨNG DỤNG AI · AI PROBABLY BETTER | DAY 02 · 36 / 83"
 },
 {
  "doc": "d2",
  "page": 15,
  "title": "Khi nào AI KHÔNG tốt hơn?",
  "key": [
   "nào",
   "tốt",
   "hơn",
   "sáu",
   "trường",
   "hợp",
   "pair",
   "gọi",
   "probably",
   "not",
   "better",
   "chương",
   "cần",
   "duy"
  ],
  "text": "Khi nào AI KHÔNG tốt hơn? | — Sáu trường hợp PAIR gọi là \"AI probably NOT better\" · Chương 1 | PAIR ① ② ③ | Cần duy trì tính dự đoán được | Nút Home / Cancel phải luôn nằm ở một chỗ quen thuộc — người dùng không phải đoán mỗi lần. | Lỗi quá tốn kém | Chi phí của một lần sai lớn hơn lợi ích của nhiều lần đúng. | ối ưu tốc độ & chi phí thấp ần ra thị trường nhanh (time-to-market), vận hành rẻ — AI chỉ thêm độ trễ và chi phí. | Thông tin tĩnh, ít thay đổi | - Nội dung cố định thì cứ hiển thị trực tiếp — không cần AI sinh lại mỗi lần. Yêu cầu minh bạch tuyệt đối Mọi quyết định phải giải thích được từng bước, truy vết được. | Việc giá trị cao người dùng muốn tự làm | Tác vụ mang ý nghĩa cá nhân mà người dùng KHÔNG muốn bị tự động hóa. | Rule/heuristic dễ build, dễ giải thích, dễ debug và bảo trì hơn — nếu nó giải quyết được, đó là lựa chọn tối ưu. | NGUỒN PAIR — Ch.1 User Needs + Defining Success CÓ NÊN ỨNG DỤNG AI · KHI NÀO KHÔNG CẦN AI | DAY 02 · 37 / 83"
 },
 {
  "doc": "d2",
  "page": 16,
  "title": "Hệ thống AI = Model + Context + Planning + Tools",
  "key": [
   "thống",
   "model",
   "context",
   "planning",
   "tools",
   "giải",
   "pháp",
   "thực",
   "nhiều",
   "thành",
   "phần",
   "chỉ",
   "dừng",
   "lại"
  ],
  "text": "Hệ thống AI = Model + Context + Planning + Tools | — Một giải pháp AI thực tế là một hệ thống nhiều thành phần, không chỉ dừng lại ở mô hình ngôn ngữ | MODEL | - | Tư duy & Sáng tạo | Xử lý đọc hiểu, soạn thảo, tổng hợp, phân loại và đưa ra gợi ý. | CONTEXT | Tri thức chuyên biệt | Cơ sở dữ liệu, tài liệu nghiệp vụ, hồ sơ lịch sử giúp AI phản hồi chính xác theo bối cảnh. | PLANNING | Điều phối quy trình | Tự động phân rã tác vụ phức tạp và linh hoạt điều chỉnh. | TOOLS | Liên kết hệ thống | Tích hợp CRM, database, lịch làm việc hoặc API bên thứ ba. | Giải pháp AI là một HỆ THỐNG — model chỉ là một thành phần. | NGUỒN Anthropic — Building effective agents · Chip Huyen — AI Engineering HỆ THỐNG AI · KIẾN TRÚC | DAY 02 · 42 / 83"
 },
 {
  "doc": "d2",
  "page": 17,
  "title": "Automation vs Augmentation",
  "key": [
   "automation",
   "augmentation",
   "bước",
   "pair",
   "từng",
   "tác",
   "làm",
   "thay",
   "trợ",
   "con",
   "người",
   "①②③",
   "augment",
   "chọn"
  ],
  "text": "Automation vs Augmentation | — Bước ② của PAIR: với từng tác vụ, AI nên làm thay hay hỗ trợ con người? | ①②③ | A U M AT E | AUGMENT | AI làm thay | Chọn khi: H · Việc khó, nhàm chán, nguy hiểm hoặc cần scale AT · Người dùng thiếu kiến thức / khả năng tự làm · Có \"đáp án đúng\" mà mọi người cùng đồng thuận | AI hỗ trợ con người | quyết định theo từng tác vụ | Chọn khi: | · Người dùng thích tự làm việc đó · Stakes cao: tiền bạc, pháp lý, sức khỏe · Kết quả cần trách nhiệm cá nhân / social capital · Sở thích khó diễn đạt thành lời | - Đo thành công bằng: hiệu quả tăng · an toàn hơn · giảm việc tẻ nhạt. | Đo bằng: mức độ thích thú · cảm giác kiểm soát · sáng tạo tăng. | Việc đã automate vẫn gần như luôn cần human oversight — preview, edit, undo. | NGUỒN Google PAIR — Ch.1 User Needs + Defining Success RWA · AUTOMATE VS AUGMENT | DAY 02 · 43 / 83"
 },
 {
  "doc": "d2",
  "page": 18,
  "title": "Ba mức giải pháp: Rule / Workflow / Agent",
  "key": [
   "mức",
   "giải",
   "pháp",
   "rule",
   "workflow",
   "agent",
   "cấp",
   "thuật",
   "còn",
   "automate",
   "augment",
   "pair",
   "vai",
   "trò"
  ],
  "text": "Ba mức giải pháp: Rule / Workflow / Agent | — Rule/Workflow/Agent là cấp độ KỸ THUẬT — còn Automate/Augment (PAIR) là cấp độ VAI TRÒ của con người trong hệ thống | CẤP ĐỘ 1 | CẤP ĐỘ 2 | CẤP ĐỘ 3 | Rule / Script | · Đầu vào ổn định, ít thay đổi H · Logic viết được thành if/else T · Cần kết quả luôn đúng 100% · Quy định pháp lý / tuân thủ chặt | LLM Feature / Workflow | · Đầu vào đa dạng, không viết hết rule được · Đầu ra cần linh hoạt (tóm tắt, dịch, phân loại) · Có cách đo chất lượng · Người có thể kiểm tra trước khi gửi | Agent | · Nhiều bước, dùng nhiều công cụ · Tình huống thay đổi liên tục · Cần tự ra quyết định giữa các bước · Có kiểm soát rủi ro rõ ràng | - Ví dụ: Tính thuế · chặn email spam theo từ khóa · | auto-reply theo template. | Ví dụ: Tóm tắt email · chatbot FAQ · phân loại ticket hỗ trợ. | Ví dụ: Agent nghiên cứu thị trường · coding agent sửa nhiều file. | Thứ tự ưu tiên thực dụng: bắt đầu từ bên trái, chỉ đi sang bên phải khi giá trị tăng hơn độ phức tạp. | RWA · TỔNG QUAN | DAY 02 · 45 / 83"
 },
 {
  "doc": "d2",
  "page": 19,
  "title": "Một tình huống, ba cấp độ giải pháp",
  "key": [
   "tình",
   "huống",
   "cấp",
   "giải",
   "pháp",
   "tiên",
   "đơn",
   "giản",
   "nhất",
   "thể",
   "quyết",
   "bài",
   "toán",
   "mang"
  ],
  "text": "Một tình huống, ba cấp độ giải pháp | — Ưu tiên giải pháp đơn giản nhất có thể giải quyết bài toán và mang lại cải tiến đo lường được | Ấ P Đ Ộ 1 — R U L E ( L U Ậ Ĩ ) O Trả lời tự động · Tự động trả lời FAQ, gửi link thời khóa biểu A · Gửi tài liệu sửa lỗi cài đặt cơ bản K · Nhắc nhở checklist nộp bài | CẤP ĐỘ 2 — WORKFLOW (QUY TRÌNH) | Duyệt Problem Card | · AI kiểm tra độ đầy đủ của Problem Card · Yêu cầu bổ sung nếu thiếu thông tin · Chuyển cho Trợ giảng giải quyết | CẤP ĐỘ 3 — AGENT (TÁC NHÂN) | Đề xuất can thiệp chủ động | · Tự động theo dõi tiến độ nộp bài · Phát hiện nhóm học viên bị kẹt lâu · Chuẩn bị câu trả lời, đề xuất TA duyệt | - Khi nào? Logic tường minh, kết quả cố định. | Khi nào? Có quy trình rõ, AI hỗ trợ từng bước. | Khi nào? Tình huống động, đa công cụ. | Không bắt buộc nâng cấp tuần tự từ Rule lên Agent → dừng ở cấp tối giản nhất nếu đã đáp ứng mục tiêu đề ra. | RWA · SO SÁNH | DAY 02 · 50 / 83"
 },
 {
  "doc": "d2",
  "page": 20,
  "title": "Workflow patterns — đủ cho hầu hết bài toán",
  "key": [
   "workflow",
   "patterns",
   "hầu",
   "hết",
   "bài",
   "toán",
   "hình",
   "bản",
   "theo",
   "anthropic",
   "building",
   "effective",
   "agents",
   "2024"
  ],
  "text": "Workflow patterns — đủ cho hầu hết bài toán | — Ba mô hình cơ bản theo Anthropic · Building Effective Agents (2024) | 1. Prompt Chaining | In → LLM Call 1 → Gate → LLM Call 2 → LLM Call 3 → Out | ┖ - - Gate fail → Exit | Chia task thành chuỗi bước tuần tự, có gate kiểm tra giữa các bước. VD: Viết outline → check → viết bài. | Ý nghĩa quyết định: đổi độ trễ lấy độ chính xác. | N 3. Parallelization LLM Call 1 | T In → LLM Call 2 → Aggregator → Out C LLM Call 3 | Chạy song song rồi tổng hợp (sectioning), hoặc chạy nhiều lần lấy vote. VD: | Guardrail + response đồng thời. | Ý nghĩa quyết định: vote để giảm rủi ro một đầu ra sai. | 2. Routing | - LLMCall1 In → Router → LLM Call 2 → Out LLM Call 3 | Phân loại input → đưa vào nhánh chuyên biệt, tối ưu từng loại riêng. VD: CS query → FAQ / refund / kỹ thuật. | Ý nghĩa quyết định: câu dễ đi model rẻ, câu khó đi model mạnh. | NGUYÊ ẮC ANTHROPIC | → Luôn ưu tiên giải pháp đơn giản nhất; chỉ tăng độ phức tạp khi thực sự cần thiết. | 3 mô hình cơ bản bên cạnh đã đủ đáp ứng hầu hết bài toán thực tế. | NGUỒN Anthropic — Building effective agents WORKFLOW PATTERNS · BASIC | DAY 02 · 52 / 83"
 },
 {
  "doc": "d2",
  "page": 21,
  "title": "Cây quyết định: Lựa chọn cấp độ giải pháp",
  "key": [
   "cây",
   "quyết",
   "định",
   "lựa",
   "chọn",
   "cấp",
   "giải",
   "pháp",
   "bài",
   "toán",
   "cốt",
   "lõi",
   "đến",
   "rule"
  ],
  "text": "Cây quyết định: Lựa chọn cấp độ giải pháp | — Từ bài toán cốt lõi đến lựa chọn Rule, Workflow hay Agent | Đi từ trên xuống — mỗi nhánh \"KHÔNG\" là một lần tránh được độ phức tạp không cần thiết. | NGUỒN Anthropic — Building effective agents · Google — Rules of ML WORKFLOW · DECISION TREE | DAY 02 · 55 / 83"
 },
 {
  "doc": "d2",
  "page": 22,
  "title": "Reward function: hệ thống hiểu \"đúng / sai\" thế nào? ① Nhu cầu ② Auto / Augment ③ Reward function",
  "key": [
   "reward",
   "function",
   "thống",
   "hiểu",
   "đúng",
   "sai",
   "thế",
   "nào",
   "nhu",
   "cầu",
   "auto",
   "augment",
   "pair",
   "bước"
  ],
  "text": "Reward function: hệ thống hiểu \"đúng / sai\" thế nào? ① Nhu cầu ② Auto / Augment ③ Reward function | — PAIR Bước ③ · Case: AI gợi ý câu trả lời cho câu hỏi của 1000 học viên (khóa K3 & K4) | Reward function là công thức quyết định đâu là dự đoán \"đúng\", đâu là \"sai\" — và chính nó định hình trải nghiệm người dùng cuối. Vì vậy | nó phải được thiết kế liên chức năng: tối thiểu UX × Product × Engineering cùng ngồi lại. | N B Ố Ế T Q U Ả C Ó Ể X ẢY R A — S E G Ợ I Ý C Â U T R Ả L Ờ P — T R U E P O S V E · Đ Ú N G -T Í Ự âu hỏi nghẽn thật → AI gợi ý đúng câu trả lời. Học viên được giải tỏa, A TA đỡ tải. | TN — TRUE NEGATIVE · ĐÚNG-TIÊU CỰ âu hỏi đã có tài liệu sẵn → AI không can thiệp. Đúng — không cần gợi ý gì thêm. | F P — FA L S E P O S V E · B ÁO Đ Ộ N G G I Ả - AI gợi ý câu trả lời SAI (hallucination) và gửi thẳng cho học viên → học viên đi sai hướng thực hành. | FN — FALSE NEGATIVE · BỎ SÓ ọc viên đang kẹt thật nhưng AI bỏ sót, không gợi ý → học viên vẫn chờ lâu như cũ. | Chi phí của FP và FN KHÔNG đối xứng — báo cháy giả ≠ bỏ sót đám cháy. Cân nhắc đánh đổi này là quyết định then chốt khi thiết kế reward function. | NGUỒN PAIR — Ch.1 User Needs + Defining Success REWARD · HÀM THƯỞNG | DAY 02 · 57 / 83"
 },
 {
  "doc": "d2",
  "page": 23,
  "title": "Precision ↔ Recall: đánh đổi không tránh khỏi",
  "key": [
   "precision",
   "recall",
   "đánh",
   "đổi",
   "tránh",
   "khỏi",
   "thống",
   "hai",
   "hướng",
   "vặn",
   "nút",
   "ngược",
   "nhau",
   "nhu"
  ],
  "text": "Precision ↔ Recall: đánh đổi không tránh khỏi | — Cùng một hệ thống AI, hai hướng vặn nút ngược nhau | ① Nhu cầu ② Auto / Augment ③ Reward function | PRECISION CAO | RECALL CAO | TP / (TP + FP) TP / (TP + HFNO) N Ít gợi ý — nhưng gợi ý nào cũng chắc đúng. Người dùng | ⇄ T tin vào từng gợi ý nhận được. | - Ệ QUẢ N Nhiều False Negative — bỏ sót học viên đang thực sự cần giúp. | ĐÒN BẨY | Vặn nút bên này lên, chất lượng bên kia xấu đi. | Bao trọn mọi trường hợp cần giúp — không học viên nào bị bỏ lại phía sau. | HỆ QUẢ | Nhiều False Positive — gợi ý sai nhiều, TA phải lọc lại thủ công. | Không có cấu hình đúng tuyệt đối — phải test điểm cân bằng với chính người dùng. | NGUỒN PAIR — Ch.1 User Needs + Defining Success REWARD · PRECISION ↔ RECALL | DAY 02 · 58 / 83"
 },
 {
  "doc": "d2",
  "page": 24,
  "title": "Viết tiêu chí thành công mà hành động được",
  "key": [
   "viết",
   "tiêu",
   "chí",
   "thành",
   "công",
   "hành",
   "động",
   "được",
   "pair",
   "bước",
   "metric",
   "tốt",
   "chỉ",
   "thể"
  ],
  "text": "Viết tiêu chí thành công mà hành động được | — PAIR Bước ③ · Metric tốt = chỉ số cụ thể + ngưỡng có nghĩa + hành động cụ thể | ① Nhu cầu ② Auto / Augment ③ Reward function | TEMPLATE CỦA PAIR | If {chỉ số cụ thể} for {tính năng AI} {drops below / goes above} {ngưỡng có nghĩa}, we will | N {hành động cụ thể}. | AT V Í D Ụ Đ I Ề N S Ẵ N — S E TA 1 0 0 0 H Ọ C V I Ê ếu tỷ lệ câu trả lời AI gợi ý bị TA sửa > 30% trong 2 tuần, ta sẽ hạ mức tự động về pha 1 (chỉ gợi ý, không gửi thẳng cho học viên). | - E L I S R Ư Ớ Ố T M E T R 0 1 Metric có ý nghĩa với MỌI người dùng T không? | 02 | Có nhóm nào bị ảnh hưởng tiêu cực không? | 03 | Đây là thành công của ngày 1 — còn ngày 1000 thì sao? | → Và đừng quên: lên lịch review metric định kỳ — tiêu chí thành công cũng cần được bảo trì theo thời gian. | NGUỒN PAIR — Ch.1 User Needs + Defining Success · PAIR Worksheet — User Needs (PDF) REWARD · SUCCESS CRITERIA | DAY 02 · 59 / 83"
 },
 {
  "doc": "d2",
  "page": 25,
  "title": "Khoảng cách giữa Demo và Production",
  "key": [
   "khoảng",
   "cách",
   "giữa",
   "demo",
   "production",
   "phản",
   "hồi",
   "chính",
   "xác",
   "vài",
   "lần",
   "thử",
   "chưa",
   "triển"
  ],
  "text": "Khoảng cách giữa Demo và Production | — Phản hồi chính xác trong vài lần thử chưa đủ cơ sở để triển khai hệ thống thực tế | N 0 1 · B A S E L E Thiết lập đối chứng T Đối chiếu hiệu quả với quy tắc tĩnh, nhân sự hay quy trình hiện C tại? | 02 · EVALUATION | Kiểm thử hệ thống | Bộ dữ liệu kiểm thử, kịch bản biên (edge cases) và tiêu chí nghiệm thu? | 03 · CONTROLS | Cơ chế kiểm soát | Logging, fallback, rollback và nhân sự chịu trách nhiệm? | 04 · OPERATIONS | Vận hành liên tục | Ai giám sát lỗi, cập nhật tri thức nền và tối ưu hệ thống? | - Mục tiêu Day 02 là xác định tính khả thi để tiếp tục nghiên cứu — chưa phải quyết định triển khai ngay. | NGUỒN Google — Rules of ML · Chip Huyen — AI Engineering QUYẾT ĐỊNH AI · DEMO TO PRODUCTION | DAY 02 · 61 / 83"
 },
 {
  "doc": "d2",
  "page": 26,
  "title": "Từ Problem Statement đến Eval Plan",
  "key": [
   "problem",
   "statement",
   "đến",
   "eval",
   "plan",
   "ràng",
   "giúp",
   "định",
   "hình",
   "thể",
   "tiêu",
   "chí",
   "kiểm",
   "thử"
  ],
  "text": "Từ Problem Statement đến Eval Plan | — Problem Statement rõ ràng giúp định hình cụ thể các tiêu chí kiểm thử | 01 · INPUT | 02 · TEST CASES | 03 · SUCCESS | Problem Statement | 9 trường đã hoàn chỉnh — từ Actor, H Workflow, Bottleneck đến Boundary & HITL. | Kịch bản kiểm thử | Dữ liệu thực tế và các trường hợp biên (edge cases). | Chỉ số hiệu năng | Đạt yêu cầu (pass) / Không đạt (fail) / Chuyển tiếp kiểm duyệt thủ công (HITL). | - AT TÁC VỤ ĐƠN LẺ ệ thống có phân loại chính xác các câu hỏi đầu vào không? | HIỆU NĂNG QUY TRÌNH | Nhóm học viên có hoàn thành bài lab nhanh hơn và ít kẹt hơn không? | RỦI RO & SAI SỐ | Hệ thống có phản hồi sai lệch mà không chuyển tiếp cho Lab Coach phê duyệt không? | PROBLEM STATEMENT · EVAL PLAN | DAY 02 · 62 / 83"
 },
 {
  "doc": "d2",
  "page": 27,
  "title": "Problem Statement cho hệ thống AI",
  "key": [
   "problem",
   "statement",
   "thống",
   "yếu",
   "bài",
   "toán",
   "cốt",
   "lõi",
   "quyết",
   "định",
   "actor",
   "workflow",
   "bottleneck",
   "impact"
  ],
  "text": "Problem Statement cho hệ thống AI | — 6 yếu tố bài toán cốt lõi và 3 yếu tố quyết định AI | 6 YẾU TỐ BÀI TOÁ ỐT LÕI | Actor Workflow Bottleneck Impact Success Metric Boundary | đối tượng ảnh hưởng quy trình hiện tại nút thắt tác động chỉ số thành công ranh giới | 3 YẾU TỐ QUYẾT ĐỊNH AI | Điểm AI can thiệp Mức chọn Rủi ro & HITL | decision · entry | decision · level | decision · safety | Đối tượng trực tiếp chịu ảnh hưởng bởi vấn đề. | N Quy trình vận hành hiện tại gồm các bước cụ thể nào? Khâu nào gặp tình trạng chậm trễ, sai sót, lặp lại? ổn thất lượng hóa bằng thời gian, chi phí, SLA hoặc chất lượng. Chỉ số đo lường cụ thể để xác định sự cải thiện. - H AI không được làm gì; khâu nào bắt buộc có con người. AI hỗ trợ hoặc tự động hóa ở bước cụ thể nào? | Rule / Workflow / Agent? | Phương án xử lý khi AI sai sót và quy trình phê duyệt thủ công. | PROBLEM STATEMENT · 9 TRƯỜNG | DAY 02 · 67 / 83"
 },
 {
  "doc": "d2",
  "page": 28,
  "title": "Khung ra quyết định: Go / Not Yet / No-Go",
  "key": [
   "khung",
   "quyết",
   "định",
   "not",
   "yet",
   "lập",
   "luận",
   "dựa",
   "trên",
   "tính",
   "khả",
   "thi",
   "problem",
   "statement"
  ],
  "text": "Khung ra quyết định: Go / Not Yet / No-Go | — Lập luận dựa trên tính khả thi của Problem Statement, tránh thiên kiến công nghệ | ✓ Go ⏸ Not Yet ✕ No-GoN thực hiện O Đ Ủ Đ I Ề U Ệ — Bài toán rõ ràng A — Chỉ số đo lường khả thi — Điểm can thiệp AI phù hợp A — Kiểm soát được rủi ro | tạm hoãn | CÓ TRIỂN VỌNG | — Cần bổ sung dữ liệu thực tế — Chuẩn hóa quy trình — Thiết lập chỉ số — Xác định ranh giới | không triển khai | KHÔNG PHÙ HỢP | — AI không mang giá trị vượt trội — Rủi ro vận hành quá cao — Giải pháp không dùng AI tối ưu hơn | - H Quyết định \"Not Yet\" thể hiện sự chín chắn trong tư duy thiết kế sản phẩm, không phải sự thất bại. | QUYẾT ĐỊNH · GO / NOT YET / NO-GO | DAY 02 · 70 / 83"
 },
 {
  "doc": "d2",
  "page": 29,
  "title": "Sáu nguyên tắc cốt lõi sau Day 02",
  "key": [
   "sáu",
   "nguyên",
   "tắc",
   "cốt",
   "lõi",
   "sau",
   "day",
   "kim",
   "chỉ",
   "nam",
   "thẩm",
   "định",
   "mọi",
   "xuất"
  ],
  "text": "Sáu nguyên tắc cốt lõi sau Day 02 | — Kim chỉ nam để thẩm định mọi đề xuất ứng dụng AI | 01 Brief mơ hồ không thay thế Problem Statement. | Một bản tóm tắt mơ hồ không thể thay thế cho một Problem Statement hoàn chỉnh. | 02 Mô hình hóa workflow trước khi tích hợp AI. H Bắt buộc phải mô hình hóa quy trình trước khi xem xét tích hợp giải pháp AI. | AT 03 Pain point phải được lượng hóa. K Mọi điểm đau cần được lượng hóa bằng baseline và chỉ số đo lường cụ thể. | 04 Phức tạp không đồng nghĩa với hiệu quả. Rule, Workflow và Agent là ba cấp độ khác nhau; độ phức tạp kỹ thuật không đồng nghĩa với hiệu quả tối ưu. | N - 05 Quyết định dựa trên lập luận thực tế. Quyết định Go / Not Yet / No-Go phải được thiết lập dựa trên lập luận thực tế và số liệu kiểm thử rõ ràng. | 06 Đo reward function bằng trải nghiệm người dùng, không chỉ accuracy. MỚI · PAIR Thiết kế đánh đổi precision ↔ recall theo lợi ích người dùng và kiểm chứng với người dùng thật. | NGUỒN PAIR — Ch.1 User Needs + Defining Success RECAP · 6 NGUYÊ ẮC | DAY 02 · 78 / 83"
 }
];
