SAMPLE_QUESTIONS = [
    {
        "question_id": "Q001",
        "student_id": "U001",
        "text": "Khi nào dùng RAG thay vì fine-tuning?",
        "status": "pending",
        "created_at": "2026-07-28T10:00:00Z",
    },
    {
        "question_id": "Q002",
        "student_id": "U001",
        "text": "Fine-tuning có cần GPU mạnh không?",
        "status": "pending",
        "created_at": "2026-07-28T10:01:00Z",
    },
    {
        "question_id": "Q003",
        "student_id": "U002",
        "text": "RAG với vector DB hoạt động thế nào?",
        "status": "pending",
        "created_at": "2026-07-28T10:02:00Z",
    },
    {
        "question_id": "Q004",
        "student_id": "U001",
        "text": "Attention cơ chế là gì?",
        "status": "pending",
        "created_at": "2026-07-28T10:03:00Z",
    },
    {
        "question_id": "Q005",
        "student_id": "U003",
        "text": "Prompt engineering khác fine-tuning chỗ nào?",
        "status": "pending",
        "created_at": "2026-07-28T10:04:00Z",
    },
    {
        "question_id": "Q006",
        "student_id": "U002",
        "text": "RAG có cần indexing không?",
        "status": "pending",
        "created_at": "2026-07-28T10:05:00Z",
    },
]

SAMPLE_CLASSIFICATIONS = [
    {
        "question_id": "Q001",
        "topic_id": "DAY_01_CH_14",
        "topic_title": "RAG",
        "intent": "compare",
        "confidence": "high",
        "status": "auto_grouped",
        "matched_terms": ["RAG", "fine-tuning"],
        "evidence_refs": [{"file_id": "D1", "line": 120}],
        "alternatives": [],
        "rationale": "So sánh RAG vs fine-tuning",
    },
    {
        "question_id": "Q002",
        "topic_id": "DAY_01_CH_14",
        "topic_title": "RAG",
        "intent": "clarify_concept",
        "confidence": "medium",
        "status": "auto_grouped",
        "matched_terms": ["fine-tuning"],
        "evidence_refs": [],
        "alternatives": [],
        "rationale": "Hỏi về yêu cầu fine-tuning",
    },
    {
        "question_id": "Q003",
        "topic_id": "DAY_01_CH_14",
        "topic_title": "RAG",
        "intent": "need_example",
        "confidence": "high",
        "status": "auto_grouped",
        "matched_terms": ["RAG", "vector DB"],
        "evidence_refs": [],
        "alternatives": [],
        "rationale": "Hỏi cơ chế RAG",
    },
    {
        "question_id": "Q004",
        "topic_id": "DAY_01_CH_07",
        "topic_title": "Attention",
        "intent": "clarify_concept",
        "confidence": "medium",
        "status": "auto_grouped",
        "matched_terms": ["Attention"],
        "evidence_refs": [],
        "alternatives": [],
        "rationale": "Hỏi khái niệm Attention",
    },
    {
        "question_id": "Q005",
        "topic_id": "DAY_01_CH_01",
        "topic_title": "Prompt Engineering",
        "intent": "compare",
        "confidence": "low",
        "status": "needs_review",
        "matched_terms": [],
        "evidence_refs": [],
        "alternatives": [],
        "rationale": "Chưa rõ ràng",
    },
    {
        "question_id": "Q006",
        "topic_id": "DAY_01_CH_14",
        "topic_title": "RAG",
        "intent": "clarify_concept",
        "confidence": "high",
        "status": "unmatched",
        "matched_terms": [],
        "evidence_refs": [],
        "alternatives": [],
        "rationale": "Không khớp taxonomy",
    },
    {
        "question_id": "Q007",
        "topic_id": "DAY_01_CH_14",
        "topic_title": "RAG",
        "intent": "clarify_concept",
        "confidence": "high",
        "status": "error",
        "matched_terms": [],
        "evidence_refs": [],
        "alternatives": [],
        "rationale": "Lỗi xử lý",
    },
]
