import { useState } from "react";

export default function MindmapModal({ onClose, onOpenLesson }) {
  const [activeNode, setActiveNode] = useState("center");

  return (
    <div className="modal-overlay" role="dialog" aria-modal="true">
      <div className="modal modal--mindmap">
        <button type="button" className="modal__close" onClick={onClose}>
          ✕
        </button>

        <div className="mindmap-header">
          <div className="mindmap-title">
            <span className="icon-map">🗺️</span>
            <div>
              <h2>Bản đồ Tư duy & Lỗ hổng Kiến thức (AI Mindmap)</h2>
              <p>COMP2010 — AI Product Thinking & Requirements</p>
            </div>
          </div>
          <span className="badge-ai">🤖 Auto-generated by VLearn AI</span>
        </div>

        <div className="mindmap-canvas">
          {/* Central Root Node */}
          <div className="mindmap-tree">
            <div
              className={`mindmap-node mindmap-node--root ${activeNode === "center" ? "is-active" : ""}`}
              onClick={() => setActiveNode("center")}
            >
              🎓 COMP2010: AI Product Thinking
            </div>

            <div className="mindmap-branches">
              {/* Branch Day 1 */}
              <div className="mindmap-branch">
                <div
                  className={`mindmap-node mindmap-node--day ${activeNode === "day1" ? "is-active" : ""}`}
                  onClick={() => setActiveNode("day1")}
                >
                  📌 Day 01: Foundation
                </div>
                <div className="mindmap-subnodes">
                  <div className="mindmap-subnode" onClick={() => onOpenLesson("Day01")}>
                    • Tư duy sản phẩm AI vs Software thường
                  </div>
                  <div className="mindmap-subnode" onClick={() => onOpenLesson("Day01")}>
                    • JTBD & Xác định Job Executor
                  </div>
                </div>
              </div>

              {/* Branch Day 2 */}
              <div className="mindmap-branch">
                <div
                  className={`mindmap-node mindmap-node--day ${activeNode === "day2" ? "is-active" : ""}`}
                  onClick={() => setActiveNode("day2")}
                >
                  🎯 Day 02: Bài toán & Lát cắt
                </div>
                <div className="mindmap-subnodes">
                  <div className="mindmap-subnode" onClick={() => onOpenLesson("Day02")}>
                    • 5 Tiêu chí Nghiệm thu bài toán
                  </div>
                  <div className="mindmap-subnode mindmap-subnode--gap" onClick={() => onOpenLesson("Day02")}>
                    ⚠️ Lát cắt 1 câu: User - Việc - AI - Kết quả (Cần ôn tập)
                  </div>
                </div>
              </div>

              {/* Branch Day 3 */}
              <div className="mindmap-branch">
                <div
                  className={`mindmap-node mindmap-node--day ${activeNode === "day3" ? "is-active" : ""}`}
                  onClick={() => setActiveNode("day3")}
                >
                  🛠️ Day 03: Thiết kế AI & HAX
                </div>
                <div className="mindmap-subnodes">
                  <div className="mindmap-subnode" onClick={() => onOpenLesson("Day03")}>
                    • Nguyên tắc HAX G1, G2, G9, G10
                  </div>
                  <div className="mindmap-subnode" onClick={() => onOpenLesson("Day03")}>
                    • 4 Lớp chỗ khó & Kịch bản rủi ro
                  </div>
                </div>
              </div>

              {/* Branch Day 4-6 */}
              <div className="mindmap-branch">
                <div
                  className={`mindmap-node mindmap-node--day ${activeNode === "day4" ? "is-active" : ""}`}
                  onClick={() => setActiveNode("day4")}
                >
                  🧪 Day 04-06: Evals & Validation
                </div>
                <div className="mindmap-subnodes">
                  <div className="mindmap-subnode" onClick={() => onOpenLesson("Day04")}>
                    • Xây dựng Golden Set (≥20 case)
                  </div>
                  <div className="mindmap-subnode" onClick={() => onOpenLesson("Day04")}>
                    • Quality Bar % & User Test log
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="mindmap-footer">
          <div className="mindmap-legend">
            <span>🔵 Nút bài học</span>
            <span className="gap-indicator">⚠️ Lỗ hổng kiến thức AI phát hiện</span>
          </div>
          <button type="button" className="btn-enter-course" onClick={() => onOpenLesson("Day01")}>
            Vào đọc bài giảng →
          </button>
        </div>
      </div>
    </div>
  );
}
